[project]
name = "ai-insurance-customer-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yatharth2005", email = "yatharthshukla2005@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
ai-insurance-customer-agent = "ai_insurance_customer_agent:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
